[advisories]
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
version = 2
yanked = "deny"

[licenses]
allow = ["Apache-2.0", "MIT", "Unicode-3.0"]
confidence-threshold = 0.8
exceptions = []
version = 2

[bans]
allow = []
allow-wildcard-paths = true
deny = [
  { name = "enumflags2", reason = "https://github.com/meithecatte/enumflags2/blob/a098a77fc1bda72ea66ad511bee9400dd115f763/AGENTS.md" },
  { name = "ring", reason = "https://github.com/briansmith/ring/issues/774" },
]
highlight = "all"
skip = []
skip-tree = []
wildcards = "deny"

[bans.workspace-dependencies]
duplicates = 'deny'
include-path-dependencies = true
unused = 'deny'

[sources]
allow-git = []
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
unknown-git = "warn"
unknown-registry = "warn"

[sources.allow-org]
bitbucket = []
github = []
gitlab = []
