# Configuration file for `prek`, a git hook framework written in Rust.
# See https://prek.j178.dev for more information.
#:schema https://www.schemastore.org/prek.json

default_env = { RUSTFLAGS = "-Dwarnings" }
default_install_hook_types = ["commit-msg", "pre-commit"]
exclude = '''
(?x)^(
  ^LICENSE
  |^CODE_OF_CONDUCT.md
  |^parser\/src\/2026-01-01.xml
  |^static\/src\/list-one.xml
)$'''

[[repos]]
hooks = [
  { id = "check-added-large-files" },
  { id = "check-case-conflict" },
  { id = "check-executables-have-shebangs" },
  { id = "check-json" },
  { id = "check-merge-conflict" },
  { id = "check-symlinks" },
  { id = "check-toml" },
  { id = "check-xml" },
  { id = "check-yaml" },
  { id = "detect-private-key" },
  { id = "end-of-file-fixer" },
  { id = "fix-byte-order-marker" },
  { id = "mixed-line-ending" },
  { id = "trailing-whitespace" },
]
repo = "builtin"

[[repos]]
hooks = [{ id = "conventional-pre-commit", stages = ["commit-msg"] }]
repo = "https://github.com/compilerla/conventional-pre-commit"
rev = "v4.4.0"

[[repos]]
hooks = [{ id = "markdownlint-cli2", language_version = "lts" }]
repo = "https://github.com/DavidAnson/markdownlint-cli2"
rev = "v0.23.3"

[[repos]]
hooks = [{ id = "yamllint" }]
repo = "https://github.com/adrienverge/yamllint.git"
rev = "v1.38.0"

[[repos]]
hooks = [{ id = "action-validator" }]
repo = "https://github.com/mpalmer/action-validator"
rev = "v0.9.0"

[[repos]]
hooks = [{ id = "cargo-deny", args = ["--all-features", "check"] }]
repo = "https://github.com/EmbarkStudios/cargo-deny"
rev = "0.20.2"

[[repos]]
hooks = [
  { id = "cargo-check", args = [
    "--all-features",
  ] },
  { id = "cargo-clippy", args = [
    "--all-features",
  ] },
  { id = "cargo-doc", args = [
    "--document-private-items",
    "--no-deps",
  ] },
  { id = "cargo-fix", args = [
    "--allow-staged",
    "--allow-dirty",
  ] },
  { id = "cargo-fmt" },
  { id = "cargo-test", args = [
    "--all-features",
  ] },
  { id = "cargo-test-doc", args = [
    "--all-features",
  ] },
  { id = "cargo-update" },
]
repo = "https://github.com/AndrejOrsula/pre-commit-cargo"
rev = "0.5.0"

[[repos]]
hooks = [
  { entry = "cargo +nightly no-std-check --manifest-path static/Cargo.toml", files = '(\.rs|Cargo\.(toml|lock))$', id = "cargo-no-std-check-static", language = "system", name = "cargo no-std-check (static)", pass_filenames = false },
]
repo = "local"
