[package]
authors.workspace = true
categories = ["data-structures", "finance", "parser-implementations"]
description = "Parser for ISO 4217 XML Data"
documentation = "https://docs.rs/iso4217-parser"
edition.workspace = true
keywords = ["currency", "iso4217"]
license.workspace = true
name = "iso4217-parser"
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
jiff = { workspace = true, features = ["std"] }
serde = { workspace = true, features = ["alloc", "derive"] }

[dev-dependencies]
quick-xml.workspace = true
yare = "3"

[lints]
workspace = true

[package.metadata.docs.rs]
all-features = true
